'use strict'

// The test suite, in order. Each entry runs in its own process from the
// repository root, as `node <file>` would. Every file runs even after one
// fails, and the failures are listed at the end: a chain that stopped at the
// first failure hid every later one until that was fixed. The list lives
// here rather than in package.json because the chain outgrew the 8191
// characters a Windows command line holds, and npm test failed there before
// running anything (1.44.0).
//
// Usage: node tests/run.js [substring]   runs only the files whose path
// contains the substring.

const { spawnSync } = require("node:child_process")
const path = require("node:path")

const FILES = [
  "test.js",
  "tests/test_removed_aot_methods.js",
  "tests/test_no_native.js",
  "tests/test_no_eval.js",
  "tests/test_property_dependencies.js",
  "tests/test_v1_dialect.js",
  "tests/test_buffer_path_parity.js",
  "tests/test_number_text_parity.js",
  "tests/test_text_path_errors.js",
  "tests/test_compiled_parity.js",
  "tests/test_compiled_extension_parity.js",
  "tests/test_buffer_gate.js",
  "tests/test_scanner_differential.js",
  "tests/test_validate_json_scanner_cost.js",
  "tests/test_buffer_reject_cost.js",
  "tests/test_nan_verdict.js",
  "tests/test_remove_additional_nested.js",
  "tests/test_exclusive_bounds.js",
  "tests/test_engine_differential.js",
  "tests/test_error_shape_differential.js",
  "tests/test_error_list_differential.js",
  "tests/test_output_format.js",
  "tests/test_standard_json_schema.js",
  "tests/test_retry_message.js",
  "tests/test_describe_schema.js",
  "tests/test_aot_parse.js",
  "tests/test_draft7_semantics.js",
  "tests/test_metaschema_ref.js",
  "tests/test_pure_js_unsupported.js",
  "tests/test_native_load_order.js",
  "tests/test_pack_purity.js",
  "tests/test_make_native_package.js",
  "tests/test_browser.js",
  "tests/test_browser_nofs.js",
  "tests/test_browser_imports_guard.js",
  "tests/test_esm_exports.js",
  "tests/test_version_sync.js",
  "tests/test_native_loaded.js",
  "tests/test_native_lazy.js",
  "tests/test_buffer_apis_without_native.js",
  "tests/test_cold_start_modules.js",
  "tests/test_safe_regex_embed.js",
  "tests/test_t_builder.js",
  "tests/test_async_refine.js",
  "tests/test_safe_regex.js",
  "tests/test_safe_regex_integration.js",
  "tests/test_regex_ecma_whitespace.js",
  "tests/test_regex_native_linear.js",
  "tests/test_aot_build.js",
  "tests/test_aot_differential.js",
  "tests/test_aot_cli_build.js",
  "tests/test_aot_cli_smoke.js",
  "tests/test_bundle_standalone.js",
  "tests/test_standalone_anyof.js",
  "tests/test_standalone_formats.js",
  "tests/test_aot_format_mode.js",
  "tests/test_aot_additional_props_errors.js",
  "tests/test_id_anchor_refs.js",
  "tests/test_engine_routing.js",
  "tests/test_engine_option.js",
  "tests/test_compile_cache_order.js",
  "tests/test_engine_diagnostic.js",
  "tests/test_format_engine_parity.js",
  "tests/test_error_accumulator_collision.js",
  "tests/test_uri_helper_parity.js",
  "tests/test_uri_fast_path.js",
  "tests/test_extend_verdict.js",
  "tests/test_ipv4_regex.js",
  "tests/test_ipv6_fast_path.js",
  "tests/test_nested_recursion_decline.js",
  "tests/test_generator_error_content.js",
  "tests/test_inherited_key_presence.js",
  "tests/test_proto_accessor.js",
  "tests/test_hybrid_tier.js",
  "tests/test_first_rejection_builds_one.js",
  "tests/test_container_local.js",
  "tests/test_one_shot_validate.js",
  "tests/test_fixed_pattern_inline.js",
  "tests/test_plan_source.js",
  "tests/test_fused_remove_additional.js",
  "tests/test_runtime_parse.js",
  "tests/test_formats_single_pass.js",
  "tests/test_email_format_cost.js",
  "tests/test_format_single_error.js",
  "tests/test_defs_pointer_alias.js",
  "tests/test_encoded_refs.js",
  "tests/test_cross_doc_root_ref.js",
  "tests/test_codegen_entrypoint_agreement.js",
  "tests/test_schema_code_injection.js",
  "tests/test_aot_html_safe.js",
  "tests/test_ref_annotation_siblings.js",
  "tests/test_gate_wrapped_schemas.js",
  "tests/test_pattern_message_escape.js",
  "tests/test_nested_defaults_engines.js",
  "tests/test_nested_coercion_parity.js",
  "tests/test_preprocess_cache.js",
  "tests/test_large_schema_codegen.js",
  "tests/test_base_uri.js",
  "tests/test_hoisted_def_recursion.js",
  "tests/test_alias_definitions.js",
  "tests/test_property_names_ref.js",
  "tests/test_hybrid_agreement.js",
  "tests/test_codegen_edge_shapes.js",
  "tests/test_deferred_def_scope.js",
  "tests/test_node_scoped_ctx_flags.js",
  "tests/test_fast_slot_exhaustion.js",
  "tests/test_ajv_errors.js",
  "tests/test_custom_keywords.js",
  "tests/test_custom_keyword_codegen.js",
  "tests/test_strict_schema.js",
  "tests/test_aot_external_checks.js",
  "tests/test_ajv_parity.js",
  "tests/test_user_format_error_path.js",
  "tests/test_unevaluated_error_path.js",
  "tests/test_unevaluated_error_shape.js",
  "tests/test_unevaluated_differential.js",
  "tests/fuzz_differential.js",
  "tests/test_pattern_properties_errors.js",
  "tests/test_additional_properties_scaling.js",
  "tests/test_additional_props_combined_cost.js",
  "tests/test_no_input_mutation.js",
  "tests/test_typed_validator_runner.js",
  "tests/test_define_schema.js",
  "tests/test_error_codes_lock.js",
  "tests/test_error_code_lookup.js",
  "tests/test_error_order.js",
  "tests/test_error_order_ordinal.js",
  "tests/test_ref_error_order.js",
  "tests/test_rejection_shape.js",
  "tests/test_lazy_normalization.js",
  "tests/test_value_equality.js",
  "tests/test_vocabulary.js",
  "tests/test_schema_scan.js",
  "tests/test_lazy_errors.js",
  "tests/test_error_read_paths.js",
  "tests/test_unique_items_error_pair.js",
  "tests/test_rich_errors_generated.js",
  "tests/test_captured_verdict_stub.js",
  "tests/test_generated_returns_rewrite.js",
  "tests/test_deep_pointer_refs.js",
  "tests/test_uneval_props_dynamic.js",
  "tests/test_one_pass_no_fallback.js",
  "tests/test_scanner_size_cap.js",
  "tests/test_scanner_index_keys.js",
  "tests/test_both_defs_containers.js",
  "tests/test_uneval_branch_counts.js",
  "tests/test_branch_verdicts.js",
  "tests/test_property_names_subschema.js",
  "tests/test_property_named_ref.js",
  "tests/test_validate_json_engines_same_errors.js",
  "tests/test_prototype_property_names.js",
  "tests/test_proto_name_rename_invariance.js",
  "tests/test_shared_definitions.js",
  "tests/test_compile_cache_bound.js",
  "tests/test_uneval_items_dynamic.js",
  "tests/test_escaped_property_names.js",
  "tests/test_ref_siblings_combined.js",
  "tests/test_unicode_property_patterns.js",
  "tests/test_cold_twin.js",
  "tests/test_native_positions.js",
  "tests/test_validate_json_single_parse.js",
  "tests/test_single_pass_errors.js",
  "tests/test_lazy_json_errors.js",
  "tests/test_lazy_instance.js",
  "tests/test_cyclic_input.js",
  "tests/test_native_error_codes.js",
  "tests/test_verdict_preprocess.js",
  "tests/test_lite_parity.js",
  "tests/test_lite_bundle_size.js",
  "tests/test_defaults_own_keys.js",
  "tests/test_plan_compiler.js",
  "tests/test_nullable.js",
  "tests/test_validate_and_parse.js",
  "tests/test_validate_data.js",
  "tests/test_enrich_error.js",
  "tests/test_enrich_received.js",
  "tests/test_rich_errors_optout.js",
  "tests/test_error_messages.js",
  "tests/test_source_positions.js",
  "tests/fuzz_positions.js",
  "tests/test_malformed_json_termination.js",
  "tests/test_data_positions.js",
  "tests/test_targeted_positions.js",
  "tests/test_position_map_cost.js",
  "tests/test_targeted_positions_cost.js",
  "tests/test_aot_staleness.js",
  "tests/test_file_positions.js",
  "tests/test_aot_positions_cost.js",
  "tests/test_schema_hash.js",
  "tests/test_render_shared.js",
  "tests/test_renderers.js",
  "tests/test_render_without_process.js",
  "tests/test_additive_fields.js",
  "tests/test_diagnostic_source.js",
  "tests/test_diagnose.js",
  "tests/test_correlate.js",
  "tests/test_diagnostics_score.js",
  "tests/test_runtime_error_dx.js",
  "tests/test_aot_error_dx.js",
  "tests/test_aot_source_frames.js",
  "tests/test_abort_early.js",
  "tests/test_branch_collapse.js",
  "tests/test_suggestions.js",
  "tests/test_levenshtein_banded.js",
  "tests/test_interpreter_enum_unique.js",
  "tests/test_combined_recursive_definition.js",
  "tests/test_migrate.js",
  "tests/test_cli_validate.js",
  "tests/test_cli_version.js",
  "tests/test_collect_evaluated.js",
  "tests/test_differential_tiers.js",
  "tests/test_draft7.js",
  "tests/test_dual_path.js",
  "tests/test_keywords_codegen.js",
  "tests/test_ref_cross.js",
  "tests/test_shape_classifier.js",
  "tests/test_tier0.js",
  "benchmark/bench_aot_size.mjs",
]

const root = path.resolve(__dirname, "..")
const only = process.argv[2]
const failed = []
let ran = 0
for (const file of FILES) {
  if (only && !file.includes(only)) continue
  ran++
  const r = spawnSync(process.execPath, [file], { cwd: root, stdio: "inherit" })
  if (r.status !== 0) failed.push(`${file} (${r.signal || "exit " + r.status})`)
}
if (failed.length) {
  console.error(`\n${failed.length} of ${ran} test files failed:\n  ${failed.join("\n  ")}`)
  process.exit(1)
}
console.log(`\nall ${ran} test files passed`)
