'use strict';

// All ahead-of-time (AOT) code generation lives here so the default and browser
// entries can stay free of `fs`, `path`, and `__dirname`.
// Browser bundles get `lib/aot.browser.js` instead (see package.json `browser`
// field), which throws if anyone tries to call an AOT function from the browser.
//
// Public surface (called by index.js and ata-validator/build):
//   toStandalone(validator)
//   toStandaloneModule(validator, opts)
//   bundle(Validator, schemas, opts)
//   bundleStandalone(Validator, schemas, opts)
//   bundleCompact(Validator, schemas, opts)
//   loadBundle(Validator, mods, schemas, opts)

const { compileToJSCodegenWithErrors } = require('./js-compiler');
const SAFE_REGEX_SOURCE = require('./safe-regex-source');

// Embedded verbatim in standalone modules so the output file has no runtime
// dependency on ata-validator. ASCII fast-path plus surrogate-aware slow path.
const _CP_LEN_SOURCE = `function _cpLen(s) {
  const len = s.length;
  for (let i = 0; i < len; i++) {
    if (((s.charCodeAt(i) - 0xD800) >>> 0) < 0x400) {
      let n = 0; for (const _ of s) n++; return n;
    }
  }
  return len;
}`;

// The linear-time regex engine, inlined verbatim into standalone output so a
// compiled module that uses safe `pattern` matchers has no runtime dependency
// on ata-validator. The engine source is baked into `lib/safe-regex-source.js`
// at build time (see `scripts/regen-safe-regex-source.js`), so this path has
// no `fs`/`path`/`__dirname` reads — safe in browser bundles too. The embed
// strips the strict directive and CommonJS exports and adds the `__ataSafeRe`
// alias the emitted code calls. The engine has no eval/new Function, so the
// embed is CSP-safe.
let _safeRegexEmbed = null;
function getSafeRegexEmbed() {
  if (_safeRegexEmbed === null) {
    const body = SAFE_REGEX_SOURCE
      .replace(/^'use strict'\s*\n/, '')
      .replace(/\nmodule\.exports[^\n]*\n?/, '\n');
    _safeRegexEmbed = body.trimEnd() + '\nconst __ataSafeRe = compileSafe;';
  }
  return _safeRegexEmbed;
}

// Returns the engine embed when any supplied compiled function references the
// safe matcher (jsFn._usesSafeRe), else an empty string so non-pattern modules
// pay zero bytes.
function safeRePrelude(...fns) {
  return fns.some((f) => f && f._usesSafeRe) ? getSafeRegexEmbed() + '\n' : '';
}

// A validator can enforce more than its schema says. `withKeywords` from
// @ata-project/keywords wraps an instance's entry points, and a wrapper
// declares that by setting `_externalChecks`. The emitters below build their
// module from the compiled schema alone, so a wrapped instance would emit a
// module that accepts documents the validator itself rejects. Refuse instead.
// Declining to compile is recoverable. A module that wrongly accepts is not.
function assertEmittable(validator, fnName) {
  if (validator._usesKeywords) {
    throw new Error(fnName + ': a schema that uses custom keywords cannot be compiled into a standalone module (option "keywords")');
  }
  if (validator._externalChecks) {
    throw new Error(fnName + ': this validator enforces checks that are not in its schema, so a standalone module would be weaker than the validator it came from. Those checks come from a wrapper such as withKeywords() from @ata-project/keywords, and JSON Schema has no spelling for them. Compile the unwrapped validator if the extra checks are not needed.');
  }
}

// --- Standalone pre-compilation ---
// Generate a JS module string that can be written to a file.
// On next startup, load with Validator.fromStandalone() -- zero compile time.
function toStandalone(validator) {
  assertEmittable(validator, 'toStandalone');
  validator._ensureCompiled();
  const jsFn = validator._jsFn;
  if (!jsFn || !jsFn._source) return null;
  const src = jsFn._source;
  const hybridSrc = jsFn._hybridSource || '';
  const preambleSrc = jsFn._preambleSource || '';

  // Also capture error function source for zero-compile standalone load
  const jsErrFn = compileToJSCodegenWithErrors(
    typeof validator._schemaObj === 'object' ? validator._schemaObj : {},
  );
  const errSrc = jsErrFn && jsErrFn._errSource ? jsErrFn._errSource : '';

  return `// Auto-generated by ata-validator — do not edit
'use strict';
${_CP_LEN_SOURCE}
${safeRePrelude(jsFn, jsErrFn)}${preambleSrc}
const boolFn = function(d) {
  ${src}
};
const hybridFactory = function(R, E) {
  return function(d) {
    ${hybridSrc}
  };
};
${errSrc ? `const errFn = function(d, _all) {\n  ${errSrc}\n};` : 'const errFn = null;'}
module.exports = { boolFn, hybridFactory, errFn };
`;
}

// --- Fully standalone module ---
// Generates a self-contained module that can be imported directly without
// pulling in ata-validator at runtime. Browser bundle gets only the
// generated validator (~2 KB typical) instead of the 165 KB compiler.
//
//   import { validate, isValid } from './user-validator.mjs'
//   if (isValid(data)) { ... }
//
// format: 'esm' | 'cjs'. Default 'esm'.
// abortEarly: if true, invalid result is a shared stub; smaller output.

// Custom format functions in standalone output.
//
// 'embed' (default) writes each function's source into the module through
// Function#toString. That only works for a plain function: one that closes
// over nothing and is not rewritten by a coverage or transpile step (istanbul
// injects `cov_` counters; a bundler may hoist helpers). The check below
// rejects those at build time with a named error instead of emitting a module
// that throws on first use.
//
// 'inject' writes no function source. The module exports `setFormats(map)`
// and each format is looked up from that registry when a value is checked,
// so the caller supplies the functions at load time.
function emitFormatDecls(closures, mode, declKW) {
  if (!closures || closures.length === 0) return { decls: '', exportsSetFormats: false };
  if (mode === 'inject') {
    let out = `${declKW} __formats = Object.create(null);\n`;
    out += `function setFormats(map) { for (const k in map) __formats[k] = map[k]; }\n`;
    for (const { name, format } of closures) {
      const key = JSON.stringify(format === null ? name.slice(4) : format);
      out += `${declKW} ${name} = function (v) { const f = __formats[${key}]; if (typeof f !== 'function') throw new Error('ata: format ' + ${key} + ' is not registered; call setFormats({ [' + ${key} + ']: fn }) before validating'); return f(v); };\n`;
    }
    return { decls: out, exportsSetFormats: true };
  }
  let out = '';
  for (const { name, fn, format } of closures) {
    const src = fn.toString();
    const label = format === null ? name : format;
    if (/\bcov_[A-Za-z0-9_$]+\b/.test(src)) {
      throw new Error(`ata: custom format "${label}" is instrumented for coverage and cannot be embedded; use { formatMode: 'inject' } and register it with setFormats() at load time`);
    }
    try {
      // eslint-disable-next-line no-new-func
      new Function('return (' + src + ')');
    } catch {
      throw new Error(`ata: custom format "${label}" has no standalone source (a bound function, a class method, or a native); use { formatMode: 'inject' } and register it with setFormats() at load time`);
    }
    out += `${declKW} ${name} = ${src};\n`;
  }
  return { decls: out, exportsSetFormats: false };
}

// Emit an expression that rebuilds `access` from the properties the schema
// declares, dropping everything else. This is the sanitising counterpart to
// removeAdditional: instead of enumerating the input and deleting the keys
// that do not belong, it reads only the keys that do. That is O(schema)
// rather than O(input), it leaves the caller's object untouched, and it keeps
// one hidden class instead of walking the object through a transition per
// delete.
//
// Returns null when the clone cannot be proven exact, and the module then
// simply has no parse(). Declining is recoverable; a sanitiser that quietly
// drops a property the schema allows is not.
function emitClone(node, access, depth) {
  if (!node || typeof node !== 'object') return null;
  if (depth > 12) return null;
  // Only plain object nodes are cloneable, and only when the schema names
  // every property it keeps. A union type, a $ref, or any composition means
  // the set of allowed keys is not this node's to decide.
  if (node.$ref || node.allOf || node.anyOf || node.oneOf || node.not ||
      node.if || node.patternProperties || node.unevaluatedProperties ||
      node.additionalProperties === true ||
      (node.additionalProperties && typeof node.additionalProperties === 'object')) {
    return null;
  }
  if (node.type !== 'object' || !node.properties) return null;
  const keys = Object.keys(node.properties);
  if (keys.length === 0) return null;
  const required = new Set(Array.isArray(node.required) ? node.required : []);

  // A property is copyable only when the emitter can name everything that
  // may live under it: a primitive holds nothing, and an object with declared
  // properties is rebuilt the same way. A $ref, a composition, an array of
  // objects or an untyped node could all carry keys this code cannot see, and
  // copying the reference would smuggle them into a value that claims to be
  // sanitised, so the whole clone is declined instead.
  const PRIMITIVE = new Set(['string', 'number', 'integer', 'boolean', 'null']);
  const fixed = [];
  const conditional = [];
  for (const key of keys) {
    const prop = node.properties[key];
    if (!prop || typeof prop !== 'object') return null;
    if (prop.$ref || prop.allOf || prop.anyOf || prop.oneOf || prop.not || prop.if) return null;
    const read = `${access}[${JSON.stringify(key)}]`;
    let value;
    const types = Array.isArray(prop.type) ? prop.type : [prop.type];
    if (types.every((t) => PRIMITIVE.has(t))) {
      value = read;
    } else if (prop.type === 'object' && prop.properties) {
      const nested = emitClone(prop, read, depth + 1);
      if (!nested) return null;
      // The nested schema may also admit null, in which case there is nothing
      // to rebuild and the value passes through.
      value = required.has(key) ? nested : nested;
    } else if (prop.type === 'array' && prop.items && typeof prop.items === 'object' &&
               !Array.isArray(prop.items) &&
               (Array.isArray(prop.items.type) ? prop.items.type : [prop.items.type])
                 .every((t) => PRIMITIVE.has(t))) {
      // An array of primitives has nowhere to hide a key. The reference is
      // shared with the input, exactly as a shallow strip would leave it.
      value = read;
    } else if (prop.type === 'array' && prop.items && typeof prop.items === 'object' &&
               !Array.isArray(prop.items) && prop.items.type === 'object' &&
               prop.items.properties) {
      // An array of objects: rebuild each element the same way, so unknown
      // keys inside the array are dropped too. Most real schemas have one of
      // these, and declining them left parse() emitted only for shapes nobody
      // writes.
      const el = '_e' + depth;
      const inner = emitClone(prop.items, el, depth + 1);
      if (!inner) return null;
      value = `${read}.map((${el}) => (${inner}))`;
    } else {
      return null;
    }
    if (required.has(key)) fixed.push(`${JSON.stringify(key)}: ${value}`);
    else conditional.push({ key, value });
  }
  if (fixed.length === 0 && conditional.length === 0) return null;

  const literal = `{ ${fixed.join(', ')} }`;
  if (conditional.length === 0) return literal;
  // Optional properties are added only when present, so the result never
  // gains a key the input did not have.
  const tmp = `_c${depth}`;
  const adds = conditional
    .map(({ key, value }) => `if (${JSON.stringify(key)} in ${access}) ${tmp}[${JSON.stringify(key)}] = ${value};`)
    .join(' ');
  return `(function(){ const ${tmp} = ${literal}; ${adds} return ${tmp}; })()`;
}

function toStandaloneModule(validator, opts) {
  assertEmittable(validator, 'toStandaloneModule');
  validator._ensureCompiled();
  const jsFn = validator._jsFn;
  if (!jsFn || !jsFn._source) return null;
  const format = (opts && opts.format) || 'esm';
  const abortEarly = !!(opts && opts.abortEarly);
  const source = !!(opts && opts.source);
  const sourceMap = opts && opts.sourceMap ? opts.sourceMap : null;
  const schemaFile = opts && opts.schemaFile ? opts.schemaFile : null;
  const src = jsFn._source;

  let errCore = '';
  let jsErrFn = null;
  if (!abortEarly) {
    jsErrFn = compileToJSCodegenWithErrors(
      typeof validator._schemaObj === 'object' ? validator._schemaObj : {},
      null,
      validator._userFormats,
      (source && sourceMap && schemaFile) ? { sourceMap, schemaFile } : null,
    );
    const errSrc = jsErrFn && jsErrFn._errSource ? jsErrFn._errSource : '';
    if (errSrc) {
      errCore = `const errFn = function(d, _all) {\n  ${errSrc}\n};\n`;
    } else if (opts && typeof opts.onWarning === 'function') {
      // The caller asked for error detail and is not getting it: the error
      // generator declined this schema (unevaluated* and a few other shapes),
      // and a standalone module has no interpreted engine to fall back to the
      // way the runtime validator does. The module still ships, with the
      // verdict exact, but every failure reports the single ATA9000 stub.
      // Silence here cost a user a debugging session; hence the channel.
      opts.onWarning(
        'error detail could not be generated for this schema; the module reports failures as the single ATA9000 abort-early error. The verdict is unaffected. For detailed errors, validate failing documents with the runtime Validator.'
      );
    }
  }

  // Schema-source frames are baked as literals inside each emitted error so
  // consumers don't need a runtime lookup. We still expose the schema file
  // as a sentinel constant when --source is on — handy for introspection
  // and visible in source graphs. With --no-source, the constant is omitted
  // entirely so size budgets and grep-based "is this source-mapped?" checks
  // both work.
  const schemaSourceConst = (source && schemaFile)
    ? `const __ATA_SCHEMA_SOURCE__ = ${JSON.stringify({ file: schemaFile })};\n`
    : '';

  // Serialize closure vars referenced in _fn body: regex, sub-validators, sets.
  let closureDecls = '';
  if (jsFn._closures && jsFn._closures.length > 0) {
    const lines = [];
    for (const { name, val } of jsFn._closures) {
      if (Array.isArray(val)) {
        lines.push(`const ${name} = ${JSON.stringify(val)};`);
        continue;
      }
      if (val && val.__ataSafe) {
        lines.push(`const ${name} = __ataSafeRe(${JSON.stringify(val.source)});`);
      } else if (val instanceof RegExp) {
        const flags = val.flags;
        lines.push(`const ${name} = new RegExp(${JSON.stringify(val.source)}${flags ? ', ' + JSON.stringify(flags) : ''});`);
      } else if (val instanceof Set) {
        lines.push(`const ${name} = new Set(${JSON.stringify([...val])});`);
      } else if (typeof val === 'function') {
        // new Function('_ppv', body) — extract body from toString()
        const str = val.toString();
        // Matches: "function anonymous(_ppv\n) {\nbody\n}" or "function(_ppv){body}"
        const m = str.match(/^function[^(]*\([^)]*\)\s*\{([\s\S]*)\}$/)
        const body = m ? m[1].trim() : str;
        lines.push(`const ${name} = function(_ppv) { ${body} };`);
      }
    }
    if (lines.length) closureDecls = lines.join('\n') + '\n';
  }

  // A few helpers are self-contained and named the same wherever they appear,
  // the email check being the big one at about 2.7 KB. The boolean function
  // and the error function each hoisted their own copy, so every module that
  // used a format carried it twice. They are declared once at module scope
  // here and removed from both bodies. Everything else in the preamble stays
  // where it is: emitConstant and the generated branch checks name things per
  // compilation, and two of them at module scope would collide.
  const sharedDecls = [];
  {
    const seen = new Set();
    for (const fn of [jsFn, jsErrFn]) {
      if (!fn || !fn._sharedHelpers) continue;
      for (const h of fn._sharedHelpers) if (!seen.has(h)) { seen.add(h); sharedDecls.push(h); }
    }
    if (sharedDecls.length && errCore) {
      for (const h of sharedDecls) errCore = errCore.split(h).join('');
    }
  }
  const sharedBlock = sharedDecls.length ? sharedDecls.join('\n') + '\n' : '';

  // Hoisted oneOf/anyOf branch checks live in the boolean fn's preamble (the
  // runtime emits them before the function). The standalone module must declare
  // them at module scope too, or _fn references undefined names (e.g. _af1_b0).
  const sharedSet = new Set(sharedDecls);
  const preambleParts = jsFn._preambleParts
    ? jsFn._preambleParts.filter((part) => !sharedSet.has(part))
    : null;
  const preambleBody = preambleParts !== null
    ? (preambleParts.length ? preambleParts.join('\n  ') + '\n  ' : '')
    : (jsFn._preambleSource || '');
  const preambleDecls = preambleBody || (jsFn._preambleGuard || '')
    ? (jsFn._preambleParts ? (jsFn._preambleGuard || '') + preambleBody : preambleBody) + '\n'
    : '';

  // User-supplied format functions are referenced as _uf_<name> by both the
  // boolean (_fn) and error (errFn) bodies. Embed them via Function#toString
  // so the standalone module stays self-contained.
  const fmt = emitFormatDecls(jsFn._formatClosures, opts && opts.formatMode, 'const');
  const formatDecls = fmt.decls;

  const validBody = errCore
    ? 'return _fn(data) ? VALID : { valid: false, errors: errFn(data, true).errors }'
    : 'return _fn(data) ? VALID : ABORT';

  // parse(): validate, then hand back a copy holding only the properties the
  // schema declares. Off by default: it costs bytes in every emitted module,
  // and the reason to compile a schema ahead of time is usually to ship as
  // little as possible. Ask for it with { parse: true }.
  const cloneExpr = !(opts && opts.parse) ? null : emitClone(
    typeof validator._schemaObj === 'object' ? validator._schemaObj : null,
    'data',
    0,
  );
  // Named _ataParse rather than parse: the emitted module also carries the
  // safe-regex prelude, which has a module-scope parse() of its own for
  // reading patterns. A second declaration of that name shadowed it and the
  // prelude called this one instead, reaching _fn before its initialiser ran.
  const parseCore = cloneExpr
    ? `function _ataParse(data) {\n  if (!_fn(data)) { const e = new Error('validation failed'); e.name = 'AtaValidationError'; throw e; }\n  return ${cloneExpr};\n}\n`
    : '';

  const baseNames = cloneExpr ? 'validate, isValid' : 'validate, isValid';
  const names = fmt.exportsSetFormats ? baseNames + ', setFormats' : baseNames;
  const parseAlias = cloneExpr ? ', _ataParse as parse' : '';
  const parseProp = cloneExpr ? ', parse: _ataParse' : '';
  const exports = format === 'esm'
    ? `export { ${names}${parseAlias} };\nexport default { ${names}${parseProp} };\n`
    : `module.exports = { ${names}${parseProp} };\nmodule.exports.default = module.exports;\n`;

  const degradedNote = (!abortEarly && !errCore)
    ? '// NOTE: error detail was requested but could not be generated for this\n// schema; failures report the single ATA9000 abort-early error. The verdict\n// is exact. Validate failing documents with the runtime Validator for detail.\n'
    : '';
  return `// Auto-generated by ata-validator — do not edit.
// Schema is embedded; runtime has zero dependency on ata-validator.
${degradedNote}'use strict';
${_CP_LEN_SOURCE}
${safeRePrelude(jsFn, jsErrFn)}${schemaSourceConst}const VALID = Object.freeze({ valid: true, errors: Object.freeze([]) });
const ABORT = Object.freeze({
  valid: false,
  errors: Object.freeze([Object.freeze({
    code: 'ATA9000',
    message: 'validation failed',
    keyword: '__abort_early__',
    path: '',
  })]),
});
${closureDecls}${sharedBlock}${preambleDecls}${formatDecls}const _fn = function(d) {
  ${src}
};
${errCore}function isValid(data) { return _fn(data); }
function validate(data) { ${validBody}; }
${parseCore}${exports}`;
}

// Bundle multiple validators into a single JS file for fast startup.
// Usage:
//   const bundle = Validator.bundle([schema1, schema2, ...]);
//   fs.writeFileSync('validators.js', bundle);
//   // On startup:
//   const validators = Validator.loadBundle(require('./validators.js'), [schema1, schema2, ...]);
function bundle(Validator, schemas, opts) {
  if (opts && opts.keywords && Object.keys(opts.keywords).length > 0) {
    throw new Error('bundle: custom keywords cannot be compiled into a standalone module (option "keywords")');
  }
  const parts = schemas.map((schema) => {
    const v = new Validator(schema, opts);
    const standalone = toStandalone(v);
    if (!standalone) return 'null';
    return (
      '(function(){' +
      standalone
        .replace("'use strict';", '')
        .replace('module.exports = ', 'return ') +
      '})()'
    );
  });
  return "'use strict';\nmodule.exports = [\n" + parts.join(',\n') + '\n];\n';
}

// Zero-dependency self-contained bundle — no require('ata-validator') needed at runtime.
// opts.format: 'cjs' (default) or 'esm'.
// opts.formats: { name: fn } — embedded in the output via Function#toString.
function bundleStandalone(Validator, schemas, opts) {
  // A custom keyword is a function, and a standalone module imports nothing,
  // so there is no way to carry it. Refuse rather than emit a module that
  // silently ignores the keyword.
  if (opts && opts.keywords && Object.keys(opts.keywords).length > 0) {
    throw new Error('bundleStandalone: custom keywords cannot be compiled into a standalone module (option "keywords")');
  }
  // Cross-schema $ref resolution: only meaningful when at least one schema has
  // an $id. Skip the schemas-as-map plumbing when none of them do.
  const haveIds = schemas.some((s) => s && typeof s === 'object' && s.$id);
  const bundleOpts = haveIds ? { ...(opts || {}), schemas } : (opts || {});
  const format = (opts && opts.format) || 'cjs';
  const R = 'Object.freeze({valid:true,errors:Object.freeze([])})';
  let bundleUsesSafeRe = false;
  let bundleInjects = false;
  // Pass one compiles; pass two emits. The helpers that several schemas hoist
  // are the same text declaring the same name, so the bundle keeps one copy at
  // module scope, and pass two needs to know the set before it writes anything.
  const compiledEntries = schemas.map((schema) => {
    const v = new Validator(schema, bundleOpts);
    v._ensureCompiled();
    const jsFn = v._jsFn;
    if (!jsFn || !jsFn._hybridSource) return null;
    // The schema the validator compiled, not the one the caller passed. They
    // differ whenever anything prepared the schema: draft-07 normalization,
    // `format` removed under assertFormat: false, keywords outside the
    // dialect's vocabularies. Reading the original here would leave the
    // boolean path and the error path disagreeing about the same document.
    const jsErrFn = compileToJSCodegenWithErrors(
      v._schemaObj,
      v._schemaMap,
      v._userFormats,
    );
    if (jsFn._usesSafeRe || (jsErrFn && jsErrFn._usesSafeRe)) bundleUsesSafeRe = true;
    return { v, jsFn, jsErrFn };
  });

  const sharedDecls = [];
  {
    const seen = new Set();
    for (const e of compiledEntries) {
      if (!e) continue;
      for (const fn of [e.jsFn, e.jsErrFn]) {
        if (!fn || !fn._sharedHelpers) continue;
        for (const h of fn._sharedHelpers) if (!seen.has(h)) { seen.add(h); sharedDecls.push(h); }
      }
    }
  }
  const sharedSet = new Set(sharedDecls);

  const fns = compiledEntries.map((e) => {
    if (!e) return 'null';
    const { v, jsFn, jsErrFn } = e;
    let errBody =
      jsErrFn && jsErrFn._errSource
        ? jsErrFn._errSource
        : "return{valid:false,errors:[{code:'error',path:'',message:'validation failed'}]}";
    for (const h of sharedDecls) errBody = errBody.split(h).join('');
    // Custom format closures: embedded, or bound to the bundle-level
    // registry when opts.formats is 'inject'.
    let preamble = '';
    if (jsFn._formatClosures) {
      const f = emitFormatDecls(jsFn._formatClosures, opts && opts.formatMode, 'var');
      preamble = f.decls.replace(/^var __formats = [^\n]*\n|^function setFormats[^\n]*\n/gm, '');
      if (f.exportsSetFormats) bundleInjects = true;
    }
    // Include hoisted anyOf/oneOf branch helpers (e.g. `_af1_b0`) so the
    // bundle output is self-contained, minus anything lifted to module scope.
    const kept = jsFn._preambleParts
      ? jsFn._preambleParts.filter((part) => !sharedSet.has(part))
      : null;
    const preambleSrc = kept !== null
      ? (jsFn._preambleGuard || '') + (kept.length ? kept.join('\n  ') + '\n  ' : '')
      : (jsFn._preambleSource || '');
    if (preambleSrc) preamble = preamble ? `${preamble}\n${preambleSrc}` : preambleSrc;
    if (opts && opts.verbose) {
      // Embed the schema and a small resolver so errors carry parentSchema.
      const schemaLit = JSON.stringify(v._schemaObj);
      return `(function(R){${preamble}var _S=${schemaLit};function _PS(p){if(!p||p[0]!=='#')return undefined;var s=p.slice(1);if(!s)return _S;var ps=s.split('/').filter(Boolean).map(function(x){return x.replace(/~1/g,'/').replace(/~0/g,'~')});var t=_S;for(var i=0;i<ps.length-1;i++){if(t==null||typeof t!=='object')return undefined;t=t[ps[i]]}return t}var E=function(d){var _all=true;${errBody}};var _v=function(d){${jsFn._hybridSource}};return function(d){var r=_v(d);if(r&&r.valid===false&&r.errors){var es=[];for(var i=0;i<r.errors.length;i++){var e=r.errors[i];es.push(Object.assign({},e,{parentSchema:_PS(e.schemaPath)}))}return{valid:false,errors:es}}return r}})(R)`;
    }
    return `(function(R){${preamble}var E=function(d){var _all=true;${errBody}};return function(d){${jsFn._hybridSource}}})(R)`;
  });
  const arr = `[${fns.join(',')}]`;
  const safeEmbed = (bundleUsesSafeRe ? getSafeRegexEmbed() + '\n' : '') +
    (sharedDecls.length ? sharedDecls.join('\n') + '\n' : '');
  const registry = bundleInjects
    ? `var __formats=Object.create(null);\nfunction setFormats(map){for(var k in map)__formats[k]=map[k]}\n`
    : '';
  if (format === 'esm') {
    const extra = bundleInjects ? 'export { validators, setFormats };' : 'export { validators };';
    return `// Auto-generated by ata-validator — do not edit\n${safeEmbed}${registry}const R=${R};\nconst validators=${arr};\nexport default validators;\n${extra}\n`;
  }
  const attach = bundleInjects ? 'module.exports.setFormats=setFormats;\n' : '';
  return `'use strict';\n${safeEmbed}${registry}var R=${R};\nmodule.exports=[${fns.join(',')}];\n${attach}`;
}

// Compact bundle: deduplicated code. Shared template functions + per-schema params.
// Much smaller file → faster V8 parse → faster startup.
// opts.format: 'cjs' (default) or 'esm'.
function bundleCompact(Validator, schemas, opts) {
  if (opts && opts.keywords && Object.keys(opts.keywords).length > 0) {
    throw new Error('bundleCompact: custom keywords cannot be compiled into a standalone module (option "keywords")');
  }
  const haveIds = schemas.some((s) => s && typeof s === 'object' && s.$id);
  const bundleOpts = haveIds ? { ...(opts || {}), schemas } : (opts || {});
  const format = (opts && opts.format) || 'cjs';
  let bundleUsesSafeRe = false;
  // Analyze schemas and group by structure
  const entries = schemas.map((schema) => {
    const v = new Validator(schema, bundleOpts);
    v._ensureCompiled();
    const jsFn = v._jsFn;
    if (!jsFn || !jsFn._hybridSource) return null;
    // The schema the validator compiled, not the one the caller passed. They
    // differ whenever anything prepared the schema: draft-07 normalization,
    // `format` removed under assertFormat: false, keywords outside the
    // dialect's vocabularies. Reading the original here would leave the
    // boolean path and the error path disagreeing about the same document.
    const jsErrFn = compileToJSCodegenWithErrors(
      v._schemaObj,
      v._schemaMap,
      v._userFormats,
    );
    if (jsFn._usesSafeRe || (jsErrFn && jsErrFn._usesSafeRe)) bundleUsesSafeRe = true;
    // Hoisted anyOf/oneOf branch helpers (e.g. `_af1_b0`) must travel with the
    // hybrid body or it references undefined names. Prepending keeps dedup honest:
    // schemas with different branch sets no longer collide on body alone.
    return {
      guard: jsFn._preambleGuard || '',
      parts: jsFn._preambleParts || null,
      preamble: jsFn._preambleSource || '',
      hybridBody: jsFn._hybridSource,
      err: jsErrFn && jsErrFn._errSource ? jsErrFn._errSource : null,
      fmt: jsFn._formatClosures || null,
      shared: [
        ...(jsFn._sharedHelpers || []),
        ...((jsErrFn && jsErrFn._sharedHelpers) || []),
      ],
    };
  });

  // A helper hoisted by several schemas is the same text declaring the same
  // name, so the bundle holds one copy at module scope rather than one per
  // schema. The rest of each preamble stays with its schema: those names are
  // per compilation and would collide.
  const sharedDecls = [];
  {
    const seen = new Set();
    for (const e of entries) {
      if (!e) continue;
      for (const h of e.shared) if (!seen.has(h)) { seen.add(h); sharedDecls.push(h); }
    }
  }
  const sharedSet = new Set(sharedDecls);
  for (const e of entries) {
    if (!e) continue;
    const kept = e.parts ? e.parts.filter((part) => !sharedSet.has(part)) : null;
    const preamble = kept !== null
      ? e.guard + (kept.length ? kept.join('\n  ') + '\n  ' : '')
      : e.preamble;
    e.hybrid = preamble ? `${preamble}\n${e.hybridBody}` : e.hybridBody;
    if (e.err) for (const h of sharedDecls) e.err = e.err.split(h).join('');
  }

  // Deduplicate function bodies — many schemas produce identical or near-identical code
  const bodyMap = new Map(); // body → index
  const bodies = [];
  const errMap = new Map();
  const errBodies = [];

  const indices = entries.map((e) => {
    if (!e) return [-1, -1];
    let hi = bodyMap.get(e.hybrid);
    if (hi === undefined) {
      hi = bodies.length;
      bodies.push(e.hybrid);
      bodyMap.set(e.hybrid, hi);
    }
    let ei = -1;
    if (e.err) {
      ei = errMap.get(e.err);
      if (ei === undefined) {
        ei = errBodies.length;
        errBodies.push(e.err);
        errMap.set(e.err, ei);
      }
    }
    return [hi, ei];
  });

  // Generate compact bundle
  const isEsm = format === 'esm';
  let out = isEsm
    ? '// Auto-generated by ata-validator — do not edit\n'
    : "'use strict';\n";
  if (bundleUsesSafeRe) out += getSafeRegexEmbed() + '\n';
  if (sharedDecls.length) out += sharedDecls.join('\n') + '\n';
  const declKW = isEsm ? 'const' : 'var';
  out += `${declKW} R=Object.freeze({valid:true,errors:Object.freeze([])});\n`;

  // User format functions are referenced as _uf_<name> by the hybrid and error
  // bodies. Collect them across all schemas (deduped by name) and embed via
  // Function#toString so the bundle stays self-contained.
  const fmtSeen = new Set();
  const fmtAll = [];
  for (const e of entries) {
    if (!e || !e.fmt) continue;
    for (const entry of e.fmt) {
      if (fmtSeen.has(entry.name)) continue;
      fmtSeen.add(entry.name);
      fmtAll.push(entry);
    }
  }
  const fmtOut = emitFormatDecls(fmtAll, opts && opts.formatMode, declKW);
  out += fmtOut.decls;

  // Shared hybrid factories
  out += `${declKW} H=[\n`;
  out += bodies
    .map((b) => `function(R,E){return function(d){${b}}}`)
    .join(',\n');
  out += '\n];\n';

  // Shared error functions
  out += `${declKW} EF=[\n`;
  out += errBodies.map((b) => `function(d){var _all=true;${b}}`).join(',\n');
  out += '\n];\n';

  // Build validators from shared templates
  const arrBody = indices
    .map(([hi, ei]) => {
      if (hi < 0) return 'null';
      if (ei >= 0) return `H[${hi}](R,EF[${ei}])`;
      return `H[${hi}](R,function(){return{valid:false,errors:[]}})`;
    })
    .join(',');
  if (isEsm) {
    out += `const validators=[${arrBody}];\nexport default validators;\nexport { validators${fmtOut.exportsSetFormats ? ', setFormats' : ''} };\n`;
  } else {
    out += `module.exports=[${arrBody}];\n`;
    if (fmtOut.exportsSetFormats) out += 'module.exports.setFormats=setFormats;\n';
  }

  return out;
}

function loadBundle(Validator, mods, schemas, opts) {
  return schemas.map((schema, i) => {
    if (mods[i]) return Validator.fromStandalone(mods[i], schema, opts);
    return new Validator(schema, opts);
  });
}

module.exports = {
  toStandalone,
  toStandaloneModule,
  bundle,
  bundleStandalone,
  bundleCompact,
  loadBundle,
};
